### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by Wkela** [varbhat/exatorrent#110]
LOG
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
-----> Go app detected
-----> Fetching jq... done
-----> Fetching stdlib.sh.v8... done
-----> 
       Detected go modules via go.mod
-----> 
       Detected Module Name: github.com/varbhat/exatorrent
-----> 
 !!    The go.mod file for this project does not specify a Go version
 !!    
 !!    Defaulting to go1.12.17
 !!    
 !!    For more details see: https://devcenter.heroku.com/articles/go-apps-with-modules#build-configuration
 !!    
-----> New Go Version, clearing old cache
-----> Installing go1.12.17
-----> Fetching go1.12.17.linux-amd64.tar.gz... done
-----> Determining packages to install
       
       Detected the following main packages to install:
       		github.com/varbhat/exatorrent
       
-----> Running: go install -v -tags heroku github.com/varbhat/exatorrent 
build github.com/varbhat/exatorrent: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
 !     Push rejected, failed to compile Go app.
 !     Push failed

![image](https://user-images.githubusercontent.com/93852376/140654231-11473cdf-1efd-4d05-bd0e-cef0c6010883.png)

**Comment by varbhat** [comment]
That's old Go version. Can't you use latest Go Version ( go 1.17) ? Also, gcc is required.

Can't you use official binary provided if that works fine?

**Comment by Wkela** [comment]
Will Try.

**Comment by Wkela** [comment]
still here
cannot find module providing package crypto/ed25519

**Comment by Wkela** [comment]
and it was updated

**Comment by varbhat** [comment]
I think that it's not issue of exatorrent, hence closing it.

If any issues, feel free to discuss
