### ISSUE TITLE
 username or password size too small

### ISSUE THREAD

**Issue by kusky3** [varbhat/exatorrent#112]
I'm getting the following error:
Unable to add admin user to adminless exatorrent instance : username or password size too small

but the username length is 7 chars
and the password lenght is >15 chars

**Comment by varbhat** [comment]
tell me how it can be reproduced?

**Comment by kusky3** [comment]
i'm using the following command (systemd):

`ExecStart=/usr/bin/exatorrent -addr 0.0.0.0 -admin myusername -cert /etc/exatorrent.crt -dir /var/lib/exatorrent/ -key /etc/exatorrent/exatorrent.key -passw
`
then i have the following:
EXAPASSWORD=REDACTED
in exatorrent.service.d/ovverride.conf

**Comment by varbhat** [comment]
If it's first run, it must work. If it's not first run, try Web UI

**Comment by kusky3** [comment]
ok, thanks. how do i "reset" the password?
do i just edit the sqlite db?

**Comment by varbhat** [comment]
![IMG_20211109_204500_793](https://user-images.githubusercontent.com/68165364/140951079-018f39bf-8546-4bcc-b599-fe227ecc21ba.jpg)
![IMG_20211109_204502_715](https://user-images.githubusercontent.com/68165364/140951107-ca3a09a6-f595-47a9-893f-acd31a918cac.jpg)


You can edit password in WebUI easily.

editing database directly can work too, but might be little risky job.

I am closing this . If any issue or suggestion do exist, please discuss :)

**Comment by kusky3** [comment]
fixed it.
i'm still a bit concerned about the log.
a more specific error description would avoid this kind of problem.
anyways thanks for the help!
