### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by tanmha** [varbhat/exatorrent#125]
it would be helpful if Chromecast Support is added

**Comment by varbhat** [comment]
Hey @tanmha ,

Can you please look at https://chromecast.link/ once?( it is created by @anacrolix who is also author of torrent library used by exatorrent)

Copy the link of video in exatorrent, paste it in chromecast.link and try to play.

I am looking forward to hear how it turned out for you.

**Comment by tanmha** [comment]
hi @varbhat, 
That web app is great. it works seamlessly 

for other people who are going to try this, use IP address of the host instead of the localhost
