### ISSUE TITLE
Download Speed Info

### ISSUE THREAD

**Issue by capriciousduck** [varbhat/exatorrent#131]
Hello.

I love using exatorrent. I hosted it on my Webdock server. It's running great.

And, could you add a feature where one can see the speed at which the torrent is being downloaded?

Thanks!

**Comment by varbhat** [comment]
@capriciousduck ,

I would love to implement this feature but this feature can be little resource intensive. I was thinking of implementing this feature and i need to find optimal way of doing it.maybe it can be calculated and shown at client side when needed. 

Currently, I don't think i will implement this feature unless good solution can be found. But, you are free to discuss.
