### ISSUE TITLE
Any plans for Win or MacOS releases?

### ISSUE THREAD

**Issue by ivanduka** [varbhat/exatorrent#15]
Hi! This project is awesome! Any plans for Win or MacOS releases?

**Comment by varbhat** [comment]
Some Progress :

https://github.com/varbhat/exatorrent/commit/cc3afc8a38a27c432ade648790ccd7e17eecb1d9

1) i cross compiled exatorrent to macos using osxcross and it's working properly . Expect some progress regarding this .
2) windows cross compiled executable has been reported to run properly by @ystyle . Also , I will check it once again (I got few errors but will try to solve them)

**Comment by varbhat** [comment]
Progress  🎉 

1. https://github.com/varbhat/exatorrent/commit/cb53f300edc3f955f02da9ce8522a8ccccba2904 : This builds exatorrent for Windows along with statically linking few DLLs necessary . I was able to run this without no issues on Fresh Installation of Windows.  Thus , I can say that I have successfully cross compiled exatorrent for windows and it's working properly.
2. https://github.com/varbhat/exatorrent/commit/cc3afc8a38a27c432ade648790ccd7e17eecb1d9 : I was able to setup osxcross properly and exatorrent works without no issues on MacOS ( both intel(amd64) and M1(arm64) ).

Thus , Expect exatorrent Releases for Windows and MacOS in v0.0.2

**Comment by Slach** [comment]
@varbhat great, thanks a lot for your efforts

**Comment by varbhat** [comment]
@Slach @ivanduka ,

https://github.com/varbhat/exatorrent/releases/tag/v0.0.2

Go Ahead, MacOS and Windows Builds have been released

**Comment by Slach** [comment]
@varbhat windows version works, but i not sure about streaming, even when I download 30% of file, web player doesn't works
 and VLC also can't open stream 
 
![image](https://user-images.githubusercontent.com/105560/132492295-974410ce-d6ba-4482-b45d-e084b53f024d.png)

**Comment by varbhat** [comment]
Did you try with "Use Streaming API" option toggled ?

**Comment by Slach** [comment]
@varbhat yes I tried, but unsuccessful
on logs, I have the following messages:

```
[INFO] 2021/09/08 16:59:47 Starting gettorrents for  adminuser
[INFO] 2021/09/08 16:59:52 Stopped gettorrents for  adminuser
[INFO] 2021/09/08 16:59:52 Starting gettorrents for  adminuser
[INFO] 2021/09/08 16:59:52 Stopped gettorrents for  adminuser
[INFO] 2021/09/08 16:59:52 Stopped Stream for  adminuser
[INFO] 2021/09/08 16:59:52 Starting gettorrentinfo for  adminuser
[WARN] 2021/09/08 16:59:59 WebSocket Unexpected Close: websocket: close 1005 (no status)
[INFO] 2021/09/08 16:59:59 User adminuser ([::1]:56816) Disconnected
[INFO] 2021/09/08 17:00:02 Stopped gettorrentinfo for  adminuser
[INFO] 2021/09/08 17:00:02 Stopped Stream for  adminuser
```

on web
![image](https://user-images.githubusercontent.com/105560/132505788-445262a5-e1c5-49b1-a8e6-ec24b7313d14.png)
and
from VLC side
![image](https://user-images.githubusercontent.com/105560/132505962-dcda0df3-3468-4ed5-b5db-964692c9ce24.png)

**Comment by varbhat** [comment]
I think that video must be downloaded more to make it streamable. Also, please also try with other torrent file.

**Comment by ystyle** [comment]
potplayer has the same issue.Neither of the provided URLs can be played

**Comment by varbhat** [comment]
@ystyle ,

1) Click on Download. Will it download.
2) Wait for File to complete download in torrent client. Will it stream?

**Comment by ystyle** [comment]
> @ystyle ,
> 
> 1. Click on Download. Will it download.
> 2. Wait for File to complete download in torrent client. Will it stream?

Download connection can be played directly on potplayer
