### ISSUE TITLE
feat support: add flag to custom password

### ISSUE THREAD

**Issue by Halimao** [varbhat/exatorrent#16]
https://github.com/varbhat/exatorrent/blob/7d3a3380af5e982245ed27cab57e500fde039db2/internal/core/init.go#L241

Just confused about using fixed passwd here...hope to add a flag like -password or else to support custom the password

**Comment by flying-sausages** [comment]
I would actually really appreciate a non-API way of setting a password as I'm configuring a script that would auto-deploy exatorrent fully pre-configured into our seedbox toolbox solution.

for example transmission does this by having a `password` option in its config file, which gets hashed when transmission starts and changed in the file. As transmission does basic auth, this allows me to "plug" the same credentials that are used for the whole system, and can manipulate them alongside the system's.

**Comment by varbhat** [comment]
@flying-sausages ,

please see this

https://github.com/varbhat/exatorrent/issues/23#issuecomment-907579056

I am thinking of implementing this by next release.

Also, you are free to suggest .

**Comment by varbhat** [comment]
@Halimao @flying-sausages ,

Please see https://github.com/varbhat/exatorrent/blob/main/docs/usage.md#-passw . You can set the password of First default user by this flag
