### ISSUE TITLE
[Feature Request] Add Support to download directly to Buckets

### ISSUE THREAD

**Issue by akashkroy** [varbhat/exatorrent#165]
It would be nice to have support downloads to S3 compatible buckets for larger files. Maybe using s3 APIs ? I am not exactly sure how that would work.

**Comment by varbhat** [comment]
@akashkroy , Thanks for asking this Question.

Actually [anacrolix/torrent](https://github.com/anacrolix/torrent) - The library we use for torrent functionality supports filesystem abstraction and as you can said, we can use S3 API to implement Torrenting directly using S3 compatible buckets as Storage layer(Not downloading to disk and uploading to S3 bucket , but directly operating on S3 bucket) .

But, the other parts of code like serving file doesn't implement this(serves from disk).

I had thought of this before , but after seeing projects like [s3fs-fuse](https://github.com/s3fs-fuse/s3fs-fuse)  I didn't pursue with idea. So,maybe try that and share your experience.

If you are talking about uploading to S3 bucket after torrent has been downloaded , I have implemented webhook which gets called when torrent gets completed. Maybe use that to implement such feature?
