### ISSUE TITLE
Why are .torrent file uploads limited to 20 MB?

### ISSUE THREAD

**Issue by Jafner** [varbhat/exatorrent#177]
Is there a technical reason, or is 20 MB just a reasonable (but arbitrary) upper limit for file size?
Is it possible for me to remove the 20 MB limit for my instance?

I have a 47 MB .torrent.

**Comment by Jafner** [comment]
I see now that it is hard coded into https://github.com/varbhat/exatorrent/blob/0b5f2c3cf2cffdc74dcaa253302180e833b71db5/internal/web/src/partials/Torrent.svelte#L34

Is this something that, in a future release, could be configured with environment variables?
Or should I fork, edit, and build from source?

**Comment by Jafner** [comment]
Editing these three files (20971520 -> 104857600, 20 MiB -> 100 MiB), building, and running in a docker container gives the following errors:

Firefox console:

![image](https://user-images.githubusercontent.com/40403594/151874294-09b8f302-494b-4b43-b063-1cecde560522.png)

Docker logs:
```
exatorrent  | [WARN] 2022/01/31 21:13:43 WebSocket Unexpected Close: websocket: close 1005 (no status)
```

Is there somewhere else I should be looking to increase the limit?

**Comment by Jafner** [comment]
Link to my changes:
https://github.com/Jafner/exatorrent/commit/d029e4be5e07e68972cc2850e4a00ddf9addd5ef

**Comment by varbhat** [comment]
@Jafner modify https://github.com/varbhat/exatorrent/blob/0b5f2c3cf2cffdc74dcaa253302180e833b71db5/internal/core/socket.go#L38

**Comment by Jafner** [comment]
Done, building now

**Comment by Jafner** [comment]
Wow, it just worked!

It takes a while before the torrent shows up in the list, but it worked!

Thank you so much @varbhat !

**Comment by varbhat** [comment]
@Jafner, I did that because I thought that 20MB is reasonable upper limit for torrent file(I still believe). Glad things are working fine after modifying.

Any suggestions are welcome.
