### ISSUE TITLE
no x86 32bit executables

### ISSUE THREAD

**Issue by mckaygerhard** [varbhat/exatorrent#213]
the title is very clear @varbhat i have a dedicated pentium4 for networking downloads.. that is not 64bit ok?

**Comment by varbhat** [comment]
I will consider it.

**Comment by varbhat** [comment]
@mckaygerhard , Now you can run exatorrent on your 32-bit potato. I have added support for x86 arch. Try it here:

https://github.com/varbhat/exatorrent/releases/download/v0.1.2/exatorrent-linux-x86

**Comment by mckaygerhard** [comment]
> I will consider it.

that "i will consider it" are hypocrit sentence, not so free software .. cos due windows 32bit bulids and inclusivelly xp support are present ..  very  interesting .. 

this issue was open to demostrate that! you provide windows binaries event said "compile it" cos you wants those to use your software event to promote open source and free software XD

**i have the pentium4 one and i will put in a level3 public ip the exatorrent now..** i am the minority so then i am not a good choice? (like ukranies, like Siria, like all the monorities of the world over the mayorities (windosers)

**Comment by mckaygerhard** [comment]
also that will be a great improvement cos any older potato device will revive with your software @varbhat

**Comment by varbhat** [comment]
@mckaygerhard 

https://github.com/varbhat/exatorrent/releases/download/v0.1.2/exatorrent-linux-x86

Try it!
