### ISSUE TITLE
Generate random password instead of using insecure defaults

### ISSUE THREAD

**Issue by OmgImAlexis** [varbhat/exatorrent#23]
> Note that Username and Password of Default User created on first run are adminuser and adminpassword respectively. You can change Password later but Username of Account can't be changed after creation. Refer Usage.

The password really shouldn't be hardcoded.

**Comment by varbhat** [comment]
@OmgImAlexis ,

It's been done for convenience. Also, I want user to change Password in Web UI. Even better, I want user to set custom username using [-admin](https://github.com/varbhat/exatorrent/blob/main/docs/usage.md#-admin) and change password in settings in Web UI.

**Comment by OmgImAlexis** [comment]
By leaving this as it is any instance that's setup is able to be taken over by any user if it's exposed to the network. 

This is a security issue, I suggest you reopen this.

**Comment by OmgImAlexis** [comment]
You closed https://github.com/varbhat/exatorrent/issues/16#issuecomment-906933505 and yet you've done the opposite here.

Are you for security or not..?

**Comment by varbhat** [comment]
@OmgImAlexis ,

Do you think passing the Initial Password of Default User as Environment variable good idea ?

I may implement this in future.

**Comment by OmgImAlexis** [comment]
Either allow passing in a environment variable or a .env file that's loaded on start up.

**Comment by varbhat** [comment]
@OmgImAlexis ,

What do you think of this.

1) you write initial password in plain text in file <exadir>/config/firstpassword 
2) exatorrent reads that file,sets password and then deletes that file.

Do you think this works ?

**Comment by varbhat** [comment]
Alright , I may implement this in next release.

**Comment by OmgImAlexis** [comment]
It works but Idk if I support that. It feels a little too much like a hack. 🤔

I wonder if there's a standard practise for this.

**Comment by varbhat** [comment]
Here's what i am thinking of.

1) There will be flag `-pass` which is boolean flag .
2) when you invoke exatorrent with `-pass` , it writes file with password at `exadir`/config/password and exits.
3) you are free to edit that file to your desired password.
4) restart exatorrent, exatorrent reads password from that file, sets password and deletes that file.

What do you think ?

**Comment by OmgImAlexis** [comment]
What about reading the password and then replacing it with a hash of the pass? That way it can stay in the file and be read each time it starts.

Otherwise what happens after it’s deleted and then restarted?

**Comment by varbhat** [comment]
Password gets saved in database.

So, accounts and password do persist between restarts :)

**Comment by flying-sausages** [comment]
In regards to the original title: random passwords are an absolute must. Either that, or a setup wizard.

In regards to the way I would suggest to configure them: I would vote for allowing `AdminPassword` and `AdminUsername` to be set in `engconfig.json`, where the password gets hashed after initialization, and the hash persist in the file. This allows for manipulation using `jq` quite effortlessly, and allows me to keep track whether the password is set correctly, and changing it over time.

**Comment by flying-sausages** [comment]
> I wonder if there's a standard practise for this.

The above is essentially how transmission does this, and it's serving me well. An environment variable is tricky, as you don't really want to store that unencrypted on the disk. If exatorrent gets triggered from a service, you'd have to define an .env file, but that would still be un-encrypted on the disk, only protected by permissions.

It would be sweet if the config could be done like this
```bash
./exatorrent -engc # Generate config
clientconfig="/home/user1/exadir/config/engconfig.json # Var for legibility
nano $clientconfig # if by interactive shell
cat <<< $(jq '.AdminPassword = WhatAL0ngpa$$w0rd' "$clientconfig")" > "$clientconfig" # workaround for in-file replace
```

**Comment by varbhat** [comment]
@OmgImAlexis @flying-sausages ,

Please see https://github.com/varbhat/exatorrent/blob/main/docs/usage.md#-passw debuted in v0.0.3 . You can set the password of First default user by this flag
