### ISSUE TITLE
MIME type issue on startup of pre-built executable (0.1.2)

### ISSUE THREAD

**Issue by drewbitt** [varbhat/exatorrent#245]
On Windows. Running exatorrent amd64 and browsing to localhost:5000 or 127.0.0.1:5000 leads to a blank page with the dev tools console error of

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```
The issue is in all modern browsers. The response header of index.js is `Content-Type: text/plain; charset=utf-8`. Manually setting :5000 or 127.0.01:5000 with -addr did not help.

**Comment by varbhat** [comment]
Yeah, I too observed the same. Unfortunately, I couldn't debug it more as I don't own the Windows machine.

Can you try it in WSL2 ?

**Comment by artunltd** [comment]
Trying to run on windows, doesn't go further than this

![image](https://user-images.githubusercontent.com/107050117/172392067-73516c3b-0c2b-4480-9b6f-5880d6c63629.png)

I saw an interface in the screenshots section

**Comment by varbhat** [comment]
Can you open http://localhost:5000 in browser?

**Comment by artunltd** [comment]
When the app works, http://localhost:5000/ shows a grey empty page, when not running: "Site can't be reached"

**Comment by drewbitt** [comment]
On Windows the frontend build when served works fine for loading signin. I did not build the entire app due to the mingw64 setup required. index.js response header is the proper `Content-Type: application/javascript; charset=utf-8`

Running amd64 version in WSL is working

**Comment by Explosion-Scratch** [comment]
Update: #258 doesn't happen to me anymore using GitPod, but some torrents get stuck on "Loading" with no reason given in logs. (Note: This could just be specific torrents)
