### ISSUE TITLE
Cannot execute arm64 binary

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#25]
I'm running Ubuntu for Arm on 20.04, and when I download the file and try to execute it, it gives arch error. I'm running this in a Multipass VM on my Apple Silicon, and I can reproduce it in a different ubuntu VM on parallels on the same machine.

```
root@swiz:/tmp# chmod +x exatorrent-linux-amd64 
root@swiz:/tmp# ./exatorrent-linux-amd64 
bash: ./exatorrent-linux-amd64: cannot execute binary file: Exec format error
root@swiz:/tmp# file ./exatorrent-linux-amd64 
./exatorrent-linux-amd64: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=de0620aef7a1f8b7d9f7ab58fd1bee298cf66dd8, stripped
```

**Comment by varbhat** [comment]
@flying-sausages ,

You are executing amd64 arch variant of exatorrent on arm64 machine.

Can you please try arm64 variant

https://github.com/varbhat/exatorrent/releases/latest/download/exatorrent-linux-arm64 

?

**Comment by FabioLolix** [comment]
That binary is for amd64 (x86_64), of course it don't run on arm

**Comment by flying-sausages** [comment]
hot damn alright I need another coffee. sorry about this, I'm embarrassed

**Comment by varbhat** [comment]
@flying-sausages ,

It's ok. I hope it runs well and you like exatorrent. Please feel to report any issues or ask for help.
