### ISSUE TITLE
Change the default port 5000 to another one. Conflict with a Synology NAS standard http port 5000

### ISSUE THREAD

**Issue by mariushosting** [varbhat/exatorrent#250]
Please change the default port 5000 to another one. Port 5000 actually is in conflict with the port 5000 on a Synology NAS device. Port 5000 is the standard http port for a Synology NAS.

**Comment by varbhat** [comment]
@mariushosting , Thank you for letting me know about this. I will change it in next release.

**Comment by varbhat** [comment]
@mariushosting , Can't you change the port of exatorrent to port other than 5000? also, ain't you using docker image in Synology?

**Comment by mariushosting** [comment]
Even if I try to change it to different one like>

docker run -d --name=exatorrent \
-p 5414:5414 \
-p 42069:42069 \
-v /volume1/docker/exatorrent:/exa/exatorrent \
--restart always \
ghcr.io/varbhat/exatorrent

I get this>


Address => :5000
Directory => exadir

[INFO] 2022/06/20 13:19:54 Adding Admin user with username "adminuser" and password "adminpassword"
[INFO] 2022/06/20 13:19:55 Torrent Client Created
[INFO] 2022/06/20 13:19:55 Starting server on :5000
[INFO] 2022/06/20 13:19:55 Loaded  20  trackers from  https://ngosang.github.io/trackerslist/trackers_best.txt
[INFO] 2022/06/20 13:19:55 Loaded  20  trackers in total , eliminating duplicates
[INFO] 2022/06/20 13:19:55 Added Loaded Trackers to Torrents
2022-06-20T13:19:55+0000 NIL [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on [::]:42069 (node id 3a852531f79813db17452f015b6ff0589a2c537a) completed bootstrap ({NumAddrsTried:13 NumResponses:0})
2022-06-20T13:20:18+0000 NIL [github.com/anacrolix/torrent.(*Client).NewAnacrolixDhtServer.func2:406]: dht server on 0.0.0.0:42069 (node id d88fb589bf3fc53ce51cff3aa893880b25037f41) completed bootstrap ({NumAddrsTried:60 NumResponses:25})

If I try to connect to the 5414 port I get blank page in the browser.
