### ISSUE TITLE
What's the Curl command to make API requests?

### ISSUE THREAD

**Issue by 0x004a** [varbhat/exatorrent#263]
Would like to make bash scripts, to automate adding, listing, and deleting torrents. Unfortunately can't work it out from the docs: https://github.com/varbhat/exatorrent/blob/main/docs/API.md

A Curl example would be great, please. Nice to see there is a Systemd unit file example.

The most awesome part of exatorrent is the daemon with RPC and async I/O.

**Comment by varbhat** [comment]
Hi @0x004a ,
exatorrent API is mostly implemented in Websocket (except Media streams which are just HTTP URLs).

To work with Websockets, it's preferred to use websocket client instead like https://github.com/vi/websocat or https://github.com/websockets/wscat . 

After connecting to API endpoint, it's just like command line shell where you enter command and get output.  You can see https://github.com/varbhat/exatorrent/blob/73de1c7b7563bf42d69f34e7b20706a8eb62c2d5/internal/core/socket.go#L108 for more insight.

**Comment by 0x004a** [comment]
An Nginx example for using exatorrent as a subfolder too please. Adding example.com/exatorrent to existing domain, that has SSL certs already and hiding the web GUI slightly.
https://github.com/varbhat/exatorrent/blob/main/docs/deploy.md

**Comment by 0x004a** [comment]
Thank you for your reply  above. Will work on it.
