### ISSUE TITLE
Request: Add unix socket path to `clientconfig.json`

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#27]
I see that you can store the definitions for the webserver in this file, and it would be nice to configure the unix socket the same way. As I'd like to make a `exatorrent@.service` file in order to allow multiple separeate sessions, this would allow me to do the config with `jq` in the specific client's config file instead of having to `sed` into the 'hardcoded' service file if I want to enable it.

**Comment by varbhat** [comment]
This can be implemented.

But , config file takes priority over files. is it ok ?

I may do this by next release

**Comment by varbhat** [comment]
Also @flying-sausages ,

Github Discussions can be used to discuss, i feel

**Comment by flying-sausages** [comment]
> But , config file takes priority over files. is it ok ?

Sorry, what do you mean by this? args override config, or config overrides args?

**Comment by flying-sausages** [comment]
> Also @flying-sausages ,
> 
> Github Discussions can be used to discuss, i feel

Feel free to convert it! I think only repo owners have the option

**Comment by varbhat** [comment]
@flying-sausages ,

Sorry, I had not enabled discussions ^_^

It's also ok to post here , nvm
