### ISSUE TITLE
"Select a torrent file" feature doesn't work in latest Firefox on Ubuntu 22.04

### ISSUE THREAD

**Issue by Sidefix** [varbhat/exatorrent#276]
As the title suggests, switching to Select a torrent file will not allow me to click the text in order to pop up the file selection dialogue under Ubuntu 22.04 on the latest Firefox build.

Works fine from Edge in Windows.

**Comment by varbhat** [comment]
I use FF both on my Linux Desktop and on Mobile. It works for me on both. Can you give me more details?

**Comment by Sidefix** [comment]
Sorry for the late reply; turns out it was an unspecified issue with my local instance. Restarting Firefox did not fix it, but a reboot of the machine in question fixed it. Thanks for looking into it.
