### ISSUE TITLE
Clarifying `ListenPort` and `ListenHost` in `clientconfig.json`, allow setting webserver values as well

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#29]
I was under the assumption that the variable names were for the webserver, but they must be for the Torrent protocol itself. 

As a reference, Transmission separates this with `peer-port` and `rpc-port`, so I would suggest using these config value names instead:
- `PeerListenHost` and `PeerListenPort`.
- `WebListenHost` and `WebListenPort` (When/if implemented).

This would make it a lot less ambiguous.

**Comment by varbhat** [comment]
@flying-sausages ,

clientconfig.json refers to torrent client only.

regarding APIs which is currently set through flags, i would consider seperate flagconfig.json which would be used instead of flags. also, i will document them.

Thus, problem will be solved

**Comment by varbhat** [comment]
@flying-sausages ,

Most values in clientconfig.json maps to 

https://github.com/anacrolix/torrent/blob/master/config.go#L23

**Comment by flying-sausages** [comment]
> i would consider seperate flagconfig.json

That sounds like a good solution, same for the unix socket!

**Comment by varbhat** [comment]
Yes. I will implement it by next release :)

**Comment by nanreh** [comment]
I vote for a simple HTTP API, one that would make it easy to integrate `exatorrent` into the *arrs applications (Sonarr, Radarr, etc). I've personally been looking for a minimalist torrent client in Go or Rust and `exatorrent` checks all the boxes but I don't see an integration yet for those popular daemons and I'd be willing to write one but not having a simple HTTP API makes it difficult.

I think it would also be nice to be able to modify configuration dynamically: like if the peer IP:port happens to change (as happens with VPN connections).
