### ISSUE TITLE
Request: Add torrents by URL of torrent file

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#30]
When magnet links are not an option, I'd like to paste the URL of the torrent itself into the WebUI instead of having to first download the file, and then uploading it.

If this is also available via API, that would offer a lot of nice possibilities for extensions from things like TamperMonkey

**Comment by varbhat** [comment]
@flying-sausages , Please see 

https://github.com/varbhat/exatorrent/issues/14#issuecomment-906598640
