### ISSUE TITLE
BaseURL support

### ISSUE THREAD

**Issue by flying-sausages** [varbhat/exatorrent#31]
I would like to run exatorrent on `domain.tld/exatorrent`, however there seems to be no flag to set this. I would suppose this is something to add to the flag-based configuration as well.

**Comment by varbhat** [comment]
@flying-sausages ,

I don't think you must be running exatorrent in different paths. subdomains(certs too are free) suit the case better. thus,i advise against these kind of setups unless there is very strong reason. better use subdomains imo.

Regarding your question, API can be served under subpath (say,by using nginx as reverse proxy).

But,see

https://github.com/varbhat/exatorrent/blob/7d3a3380af5e982245ed27cab57e500fde039db2/internal/web/src/index.html#L6

It's just made to fetch from fixed endpoint which wouldn't work when served under different subpath. Also, I don't want to change this.

In future, I will create(by forking and modifying current client) and host generic Web Client, where you will be able to Enter any API Endpoint (it might be subpath like you have mentioned) and it will just work. I also have plans to release Android App (Android client for exatorrent) in future.

**Comment by flying-sausages** [comment]
We already have all other applications and all other torrent clients configured for baseurl without the need for some complex rewrites. Baseurl is a pretty standard feature.

Domain certs are not an option as the system does not and can not modify an end-user's DNS records.

This is basically the only hard requirement we have to include apps in Swizzin, beside it compiling/running on Linux.

**Comment by Kuinox** [comment]
> I don't think you must be running exatorrent in different paths. subdomains(certs too are free) suit the case better. thus,i advise against these kind of setups unless there is very strong reason. better use subdomains imo.

I wanted to have all my config centralized in a Caddyfile but now I will have to split the config in multiple place, which is a bummer.
Plus, as all my other services runs on mydomain.com/theService , it will be very painfulls for my users.
