### ISSUE TITLE
[ERR] Error Creating Directory

### ISSUE THREAD

**Issue by NeoHBz** [varbhat/exatorrent#330]
VM: Oracle Cloud
OS: Ubuntu 22.04
Architecture: arch64

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/56602090/203585499-d34326c9-b76f-41d4-b085-ca18e954c5c2.png">

**Comment by NeoHBz** [comment]
same error on running
> docker run -p 85:5000 -v /home/neo/docker/exatorrent/data:/exa/exadir ghcr.io/varbhat/exatorrent:latest

**Comment by varbhat** [comment]
What's your user id ?

**Comment by NeoHBz** [comment]
> What's your user id ?

<img width="121" alt="image" src="https://user-images.githubusercontent.com/56602090/203590232-50d87004-c82f-45db-89a4-d40729d2b1dd.png">

**Comment by varbhat** [comment]
run with `-u` flag. by default,it runs as 1001 user-id.

**Comment by NeoHBz** [comment]
thanks, fixed it with -u flag
update run command is
> docker run -u 1002:1002 -p 85:5000 -v /home/neo/docker/exatorrent/data:/exa/exadir ghcr.io/varbhat/exatorrent:latest

**Comment by rihaq** [comment]
Now the fix is by removing /exadir from /path/to/exa-app:/exadir/exa
