### ISSUE TITLE
Consider goreleaser for releases

### ISSUE THREAD

**Issue by jalavosus** [varbhat/exatorrent#34]
It would make releases much easier on the dev end, and would enable release binaries for basically any OS/arch combo which Go supports.

**Comment by varbhat** [comment]
@jalavosus ,

I can see that you have mentioned two things in the issue.

1) Use goreleaser
2) Release for more OS and ARCH

Regarding point 1 , it's simply not necessary. Makefiles do suffice. Also goreleaser can't magically create executables if go program requires C compiler(exatorrent depends on sqlite and libutp)

Regarding point 2 , yes. I am thinking of releasing exatorrent for linux(amd64 and arm64) , macos (arm64) and windows. currently, linux versions are only released but others will eventually join the automation.
