### ISSUE TITLE
Any plan on providing the binaries to us directly via GitHub?

### ISSUE THREAD

**Issue by flavorgold1** [varbhat/exatorrent#377]
It'd be great if we didn't have to compile everything ourselves.

**Comment by mckaygerhard** [comment]
@varbhat  please.. honor UNIX life and if necesary i could provide the documentations.. but this must be in nux like way..

**Comment by dani3l0** [comment]
Hell yeah, prebuilt executable binaries would make the installation waaaay easier and quicker, especially for those who doesn't use Docker or want to build everything by themselves

**Comment by varbhat** [comment]
Yes. I used to build binaries for all major platforms. But i removed it at some point(I used to maintain build images as well which i abandoned)
