### ISSUE TITLE
Not able to build on openSUSE Leap 15.5 Beta x86_64

### ISSUE THREAD

**Issue by vinyanalista** [varbhat/exatorrent#378]
Hi! First of all, thank you for this very useful software!

I followed the [Build Docs](https://github.com/varbhat/exatorrent/blob/v1.1.0/docs/build.md) and tried to build exatorrent v1.1.0 on my laptop (64-bit PC with Linux -- the distro I use is openSUSE Leap 15.5 Beta) without success.

Here is what I did:

```
# zypper in git go1.20 gcc gcc-c++ make nodejs
$ git clone https://github.com/varbhat/exatorrent.git
$ cd exatorrent
$ git checkout v1.1.0
$ make web
$ make app
```

And here is the output I got from that last command (`make app`):

```
env CGO_ENABLED=1 go build -trimpath -buildmode=pie -ldflags '-extldflags "-static -s -w"' -o  build/exatorrent exatorrent.go
# command-line-arguments
/usr/lib64/go/1.20/pkg/tool/linux_amd64/link: running g++ failed: exit status 1
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lresolv: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lpthread: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -ldl: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lm: No such file or directory
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot find -lc: No such file or directory
collect2: error: ld returned 1 exit status

make: *** [Makefile:21: app] Error 1
```

You can reproduce the error using an [openSUSE Leap 15.5 Beta live image](https://get.opensuse.org/leap/15.5/).

Just in case it can be useful:

```
$ go version
go version go1.20.3 linux/amd64

$ node --version
v18.14.2

$ npm --version
9.5.0

$ uname -a
Linux viny-notebook 5.14.21-150500.50-default #1 SMP PREEMPT_DYNAMIC Wed Apr 19 04:27:15 UTC 2023 (965023d) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vinyanalista** [comment]
For comparison, at home I also have a Raspberry Pi 4 running [RetroPie](https://retropie.org.uk/) (based on Raspbian 10 = Debian 10 for the Raspberry Pi) and I was able to successfully build exatorrent v1.1.0 on it.

Here is what I did.

```
 # apt install curl gcc git make
```

Manually installed Go (followed instructions [here](https://www.digitalocean.com/community/tutorials/how-to-install-go-on-debian-10)):

```
$ curl -O https://dl.google.com/go/go1.20.4.linux-armv6l.tar.gz
$ sha256sum go1.20.4.linux-armv6l.tar.gz
$ tar xvf go1.20.4.linux-armv6l.tar.gz
# chown -R root:root ./go
# mv go /usr/local
$ nano ~/.profile

export GOPATH=$HOME/work
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

$ source ~/.profile
```

Manually installed Node (followed instructions [here](https://www.golinuxcloud.com/install-nodejs-and-npm-on-raspberry-pi/) and [here](https://github.com/nodesource/distributions#using-debian-as-root-1)):

```
# curl -fsSL https://deb.nodesource.com/setup_19.x | bash - &&\
apt-get install -y nodejs
```

Then, finally:

```
$ git clone https://github.com/varbhat/exatorrent.git
$ cd exatorrent
$ git checkout v1.1.0
$ make web
$ make app
```
I got built exatorrent in build directory:

```
$ cd build
$ ./exatorrent
```

Just in case it can be useful:

```
$ go version
go version go1.20.4 linux/arm

$ node --version
v19.9.0

$ npm --version
9.6.3

$ uname -a
Linux retropie 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux
```

**Comment by mckaygerhard** [comment]
i dont use crap rpm basd but such errors are just missing development libs.. nothing more.. `cannot find  lc`  its from glibc devel pacakges..  glibc-static i guess, plesae close this issue its not related to exatorrent

**Comment by varbhat** [comment]
@vinyanalista Why are you building it?

exatorrent binaries are statically linked.

I haven't tried building it on opensuse, so i don't know what's going on but exatorrent must build fine on debian(-based), arch(-based), fedora and alpine
