### ISSUE TITLE
PeerID

### ISSUE THREAD

**Issue by KamikazeePL** [varbhat/exatorrent#380]
How to set **PeerID** to fake Transmission 3.0  or Deluge?
`
[INFO] 2023/08/17 23:00:35 Torrent Client Configuration is now loaded from  exadir/config/clientconfig.json
[INFO] 2023/08/17 23:00:35 Engine Configuration {DisableLocalCache:false OnlineCacheURL: TrackerRefresh:60 TrackerListURLs:[https://ngosang.github.io/trackerslist/trackers_all.txt] DisAllowTrackersUser:false DisAllowTrackersCache:false GlobalSeedRatio:0 SRRefresh:150 DontRemoveCacheInfo:false LockbyDefault:false ListenCompletion:false HookPostURL: NotifyOnComplete:false} is now loaded
[INFO] 2023/08/17 23:00:35 PeerID of Torrent Client has been set to  -DE13F0-
panic: dest len (20) != src len (8)

goroutine 1 [running]:
github.com/anacrolix/missinggo/v2.CopyExact({0xfe80e0, 0x400015bda8}, {0x10083e0, 0x4000219d70})
        github.com/anacrolix/missinggo/v2@v2.5.3/copy.go:29 +0x4bc
github.com/anacrolix/torrent.NewClient(0x4000300000)
        github.com/anacrolix/torrent@v1.41.0/client.go:240 +0x52c
github.com/varbhat/exatorrent/internal/core.Initialize()
        github.com/varbhat/exatorrent/internal/core/init.go:284 +0x2840
main.main()
        ./exatorrent.go:15 +0x28
`

**Comment by varbhat** [comment]
exatorrent exposes Configuration Parameters of anacrolix/torrent using https://github.com/varbhat/exatorrent/blob/main/docs/usage.md#-torc . PeerID option of torc config lets you to set PeerID

See https://github.com/varbhat/exatorrent/blob/1832cae7aa6c45de25ed722d177cab774a56df6f/internal/core/vars.go#L59 for more details.

Also I apologize for my late reply.
