### ISSUE TITLE
Build Error : cannot define new methods on non-local type 

### ISSUE THREAD

**Issue by aicynide** [varbhat/exatorrent#391]
```
github.com/anacrolix/go-libutp
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:16:10: cannot define new methods on non-local type *C.utp_callback_arguments
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:24:10: cannot define new methods on non-local type *C.utp_callback_arguments
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:28:10: cannot define new methods on non-local type *C.utp_callback_arguments
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:32:10: cannot define new methods on non-local type *C.utp_callback_arguments
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:36:10: cannot define new methods on non-local type *C.utp_callback_arguments
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:29:12: cannot define new methods on non-local type *C.utp_context
/github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:40:12: cannot define new methods on non-local type *C.utp_context
make: *** [Makefile:21: app] Error 1
Error: Process completed with exit code 2.

```

**Comment by varbhat** [comment]
Yes. This is the reason and major obstacle for this project. I will take a look into it

**Comment by nlevee** [comment]
Hi, 
I made a PR to optimize docker image size that seem to fix this issue:

```
docker build -t "exatorrent" .
[+] Building 77.4s (25/25) FINISHED                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                      0.0s
 => => transferring dockerfile: 1.05kB                                                                                    0.0s
 => [internal] load .dockerignore                                                                                         0.0s
 => => transferring context: 119B                                                                                         0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                0.8s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                          0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:ac85f380a63b13dfcefa89046420e1781752bab202122f8f50032edf3  0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                0.6s
 => [internal] load metadata for docker.io/library/golang:1.20-alpine                                                     0.7s
 => [auth] library/node:pull token for registry-1.docker.io                                                               0.0s
 => [auth] library/golang:pull token for registry-1.docker.io                                                             0.0s
 => [build-node 1/5] FROM docker.io/library/node:18@sha256:7ce8b205d15e30fd395e5fa4000bcdf595fcff3f434fe75822e54e82a5f5c  0.0s
 => [build-go 1/7] FROM docker.io/library/golang:1.20-alpine@sha256:cd83dbc874245451226392246bc3f08fbae9138e9fa387dab8e9  0.0s
 => [internal] load build context                                                                                         0.0s
 => => transferring context: 56.59kB                                                                                      0.0s
 => CACHED [build-node 2/5] WORKDIR /exa                                                                                  0.0s
 => [build-node 3/5] ADD internal/web /exa/internal/web                                                                   0.1s
 => CACHED [build-go 2/7] WORKDIR /exa                                                                                    0.0s
 => CACHED [build-go 3/7] COPY go.mod go.sum ./                                                                           0.0s
 => CACHED [build-go 4/7] RUN go mod download                                                                             0.0s
 => [build-go 5/7] COPY . ./                                                                                              0.1s
 => [build-node 4/5] ADD Makefile /exa/                                                                                   0.1s
 => [build-node 5/5] RUN make web                                                                                         5.7s
 => [build-go 6/7] COPY --from=build-node /exa/internal/web/build /exa/internal/web/build                                 0.1s
 => [build-go 7/7] RUN apk add --no-cache make gcc g++ &&     make app                                                   69.4s 
 => [stage-2 1/2] COPY --from=build-go --chown=1000:1000 /exa/build/exatorrent /exatorrent                                0.1s 
 => [stage-2 2/2] WORKDIR /exa                                                                                            0.0s 
 => exporting to image                                                                                                    0.1s 
 => => exporting layers                                                                                                   0.1s 
 => => writing image sha256:8cda5252d4d46920420c59f63d2572535a70e0d68d2f16bc02a099905028af88                              0.0s 
 => => naming to docker.io/library/exatorrent                                                                             0.0s
```

**Comment by nlevee** [comment]
Hi @aicynide,

If you want I made a fork here : <https://github.com/nlevee/exatorrent> compilation work as expected

**Comment by nlevee** [comment]
Yes, I can fix it, but I'll hope this PR to pass before. 

@varbhat can you merge ? Else I can continue on my fork.

**Comment by varbhat** [comment]
@nlevee,

I am glad that you are working on improving exatorrent.

But, two things.

1) Use alpine as final image instead of scratch image. You get TLS certs managed in alpine image. In scratch, you need to copy TLS certs to the image which is not very good sign. Maybe we can look into using linuxcontainers.io images too but we can do this later.

2) Have you tried updating the deps in go.mod and compiling then? I am facing issues compiling after updating deps in go.mod probably from anacrolix/torrent packages and deps (esp. sqlite). See it if possible

**Comment by nlevee** [comment]
1. Ok, I change to alpine with ca-certificates installed.
2. No I don't try to update go.mod, the latest version of anacrolix/torrent drop compatibility with go 1.20. I have to update all deps. I'll try

**Comment by nlevee** [comment]
I fix compilation on golang 1.21 with all libraries updated ;-)

**Comment by varbhat** [comment]
@nlevee ,

Thank you very much. Can you make https://github.com/varbhat/exatorrent/pull/404/commits/da81de411603eba5d0a2c51db700fe7c590a3e2d as seperate PR?

**Comment by mckaygerhard** [comment]
@nlevee  .. i talked with @varbhat  so you can work in this now

**Comment by varbhat** [comment]
@nlevee , 

Once upon a time, we used to provide statically linked binaries for all three platforms (see  https://github.com/varbhat/exatorrent/blob/15d4e8c73d5572dedd2c504ff33d2008d1caf5ba/.github/workflows/build.yml ). But, unfortunately i couldn't maintain the toolchain i used to build exatorrent for all three platforms, and that's why i only kept docker builds.

Can you please look into it if you have time? Only linux (amd64, arm64) is desirable right now. if you have time, you can also add build definitions for linux i386, arm32. use alpine image for building as musl makes static linking a breeze.

Thank you very much. I have also invited you as collaborator.


CC: @mckaygerhard

**Comment by mckaygerhard** [comment]
@nlevee  you should still solve this issue 

bvy example you requested specific permissions not only cited by me.. also cited here:  https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/143#pullrequestreview-1618613111 

> @nlevee @aicynide there is only one issue left . the user alisaing is not the xpected case.. this fail in my system: cos in fact that useer 1000 doe snot exits in my docker image
> 
> ![image](https://user-images.githubusercontent.com/1571724/281067618-0ec03e46-21a2-4198-a378-8f7db1600f4a.png)
> 
> [main...nlevee:exatorrent:feat/optimize-dockerfile#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R34](https://github.com/varbhat/exatorrent/compare/main...nlevee:exatorrent:feat/optimize-dockerfile#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R34)

**Comment by nlevee** [comment]
> @nlevee ,
> 
> Once upon a time, we used to provide statically linked binaries for all three platforms (see https://github.com/varbhat/exatorrent/blob/15d4e8c73d5572dedd2c504ff33d2008d1caf5ba/.github/workflows/build.yml ). But, unfortunately i couldn't maintain the toolchain i used to build exatorrent for all three platforms, and that's why i only kept docker builds.
> 
> Can you please look into it if you have time? Only linux (amd64, arm64) is desirable right now. if you have time, you can also add build definitions for linux i386, arm32. use alpine image for building as musl makes static linking a breeze.
> 
> Thank you very much. I have also invited you as collaborator.
> 
> CC: @mckaygerhard

I'll take this one too yes.

Btw there's already an issue on this #377

**Comment by nlevee** [comment]
> @nlevee you should still solve this issue
> 
> bvy example you requested specific permissions not only cited by me.. also cited here: [awesome-selfhosted/awesome-selfhosted-data#143 (review)](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pull/143#pullrequestreview-1618613111)
> 
> > @nlevee @aicynide there is only one issue left . the user alisaing is not the xpected case.. this fail in my system: cos in fact that useer 1000 doe snot exits in my docker image
> > ![image](https://user-images.githubusercontent.com/1571724/281067618-0ec03e46-21a2-4198-a378-8f7db1600f4a.png)
> > [main...nlevee:exatorrent:feat/optimize-dockerfile#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R34](https://github.com/varbhat/exatorrent/compare/main...nlevee:exatorrent:feat/optimize-dockerfile#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R34)

This one was fixed in my previous PR. You can check if you want 😉

**Comment by nlevee** [comment]
> ```
> github.com/anacrolix/go-libutp
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:16:10: cannot define new methods on non-local type *C.utp_callback_arguments
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:24:10: cannot define new methods on non-local type *C.utp_callback_arguments
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:28:10: cannot define new methods on non-local type *C.utp_callback_arguments
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:32:10: cannot define new methods on non-local type *C.utp_callback_arguments
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/callbacks.go:36:10: cannot define new methods on non-local type *C.utp_callback_arguments
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:29:12: cannot define new methods on non-local type *C.utp_context
> /github/home/go/pkg/mod/github.com/anacrolix/go-libutp@v1.2.0/utp.go:40:12: cannot define new methods on non-local type *C.utp_context
> make: *** [Makefile:21: app] Error 1
> Error: Process completed with exit code 2.
> ```

You can know build locally with: 

```bash
make web && make app
```

Or with docker:

```bash
make docker
```
