### ISSUE TITLE
Archiving the project

### ISSUE THREAD

**Issue by varbhat** [varbhat/exatorrent#401]
I am archiving this project. It's mainly because of the build issue from anacrolix/torrent and crawshaw/sqlite.

I have also ideas for how to improve this project substantially. Stay tuned for future updates.

**Comment by varbhat** [comment]
unarchived because i still want to keep this updated and accept PRs

**Comment by varbhat** [comment]
Not proceeding with this. Have other plans

**Comment by mckaygerhard** [comment]
hi @varbhat i will ask in this issue , do you move the project to other places like codeberg officially or just a mirror?, i asked this personally so in holidays i can incorporate this into the taks i have delayed so i will colaborate to

**Comment by nlevee** [comment]
Hi @varbhat 
Can you pass the project in archived mode on Github ? I didn't see the issue and made PR for nothing.

I you want to continue, I can help you to fix the current bug (I think I fixed it) and collaborate for other features.

Regards
