### ISSUE TITLE
Include help or documentation per page inside UI

### ISSUE THREAD

**Issue by mckaygerhard** [varbhat/exatorrent#407]
the ui is great adn simple.. maybe we can use a markdown render to build in the help for each page.. 

this will provide both documentation for site and also embebed ui.. ! cos ui is a web also

by example:: the disconect feature

FEATURE `/ui/user/settings#Disconnect` for the Disconnect button tag or stroke
PATH `/docs/help/user/settings.md#Disconnect `( a real file tha will be embebed into the golang and rendered inside ui)

![image](https://github.com/varbhat/exatorrent/assets/1571724/5a56bf9e-a828-41a7-8ecb-5617137b4df0)

**Comment by mckaygerhard** [comment]
I have a better idea: **instead to put text in the markdown file.. just a gif with rapid steps to!**

**Comment by varbhat** [comment]
I want to rewrite  the Entire Frontend of this Application when my time permits. 

I will probably rewrite it after Svelte 5 gets released.

Also, I am thinking of further simplifying the UI by not using TailwindCSS and using https://simplecss.org/
