### ISSUE TITLE
Startup error in docker

### ISSUE THREAD

**Issue by petersem** [varbhat/exatorrent#42]
Hi, running this is docker, i get the following log errors:

```
Address => :5000
Directory => exadir
[ERR ] 2021/09/03 01:52:25 Error Creating Directory
Address => :5000
Directory => exadir
[ERR ] 2021/09/03 01:52:32 Error Creating Directory
```

Is there some kind of user permission whic needs to be passed to the container iin an environment variable?

**Comment by varbhat** [comment]
The directory name you passed must be readable/writable by user:group 1000:1000 .

I think it's unable to create directory because of permission issue. Is Directory you mounted really readable/writable by user 1000?

**Comment by petersem** [comment]
> The directory name you passed must be readable/writable by user:group 1000:1000 .
> 
> I think it's unable to create directory because of permission issue. Is Directory you mounted really readable/writable by user 1000?

Why 1000/1000? This is not standard on every linux system. For instance, on a synology nas it is 1026,101

At the moment, i have made the host folder r/w for everyone, and this works. Moving forward, it would be good to be able to pass PGID and PUID intot he container and envinment variables.

**Comment by varbhat** [comment]
@petersem ,

I understood what you told. the same issue was reported once back.

I will add ability to set UID and GID in Dockerfile.
