### ISSUE TITLE
Build error on MacOS M1 chip

### ISSUE THREAD

**Issue by detarkende** [varbhat/exatorrent#425]
I get the following error on Mac when I run `make app`:

```
env CGO_ENABLED=1 go build -trimpath -buildmode=pie -ldflags '-extldflags "-static -s -w -Wl,--allow-multiple-definition"' -o  build/exatorrent exatorrent.go
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/go-llsqlite/adapter/sqlitex
../../../../go/pkg/mod/github.com/go-llsqlite/adapter@v0.0.0-20230927005056-7f5ce7f0c916/sqlitex/sqlitex.go:19:15: undefined: errors.Join
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
make: *** [app] Error 2
```
I also got an error when I ran the latest executable from the release (although there was no trace, just "Error" or something)

Machine: Macbook Air, 2020
Chip: Apple M1
macOS version: Version 14.1.1 (23B81)

I'd love to help resolve this issue, but full disclosure: I'm not a golang dev, I mostly work on NodeJS apps. I'd like to integrate exatorrent into my app, but I need the executables for that.

**Comment by nlevee** [comment]
Hi, 

Yes there is an issue (with `sqlite` library), I removed MacOS binaries from release because it was broken.

Can you try without "-static" : 

```
env CGO_ENABLED=1 go build -trimpath -buildmode=pie -ldflags '-extldflags "-s -w -Wl,--allow-multiple-definition"' -o  build/exatorrent exatorrent.go
```

**Comment by detarkende** [comment]
I got the same error:

```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:143:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/go-llsqlite/adapter/sqlitex
../../../../go/pkg/mod/github.com/go-llsqlite/adapter@v0.0.0-20230927005056-7f5ce7f0c916/sqlitex/sqlitex.go:19:15: undefined: errors.Join
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:133:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
```

**Comment by nlevee** [comment]
I made a fix in PR #426, hope it will fix, pipeline will now work and build valid binaries

**Comment by nlevee** [comment]
Can you try with those binaries : 
https://github.com/varbhat/exatorrent/suites/18482820178/artifacts/1072267292

**Comment by detarkende** [comment]
@nlevee thank you so much. It did work. I'm not sure if these are expected, so I'll just leave them here:
- I got an error when running it in a pop up alert: "exatorrent cannot be opened because it is from an unidentified developer", but I was able to resolve it with the help of [this apple guide](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac).
- It said that port 5000 is already in use (even after killing port 5000), but when I ran it with `-addr :4200`, it ran perfectly on port 4200, so I'm assuming this is a me-issue.
- After stopping the app with Ctrl+C (not sure if this is advised), when I tried to run it on any port, it gave me the following error: ` Unable to Create Torrent Client  subsequent listen: listen udp4 :42069: bind: address already in use` - again, this might just be me not using the software correctly or having an issue with my computer.

If these are unrelated, then please disregard them. Thank you for the quick response 🙂🚀🚀🚀🚀

**Comment by nlevee** [comment]
thank you for your feedback, I can't reproduce these problems as I don't have a Mac, but if anyone comes across the problem again I'll open tickets.
