### ISSUE TITLE
About compiling with mingw in win10

### ISSUE THREAD

**Issue by ystyle** [varbhat/exatorrent#44]
1. install MSYS2 (Select x86_64 in the wizard)
2. install mingw64(All information refer to [使用 CLion + MSYS2 配置 C 语言编程环境](https://zhuanlan.zhihu.com/p/37908498))
    ```shel
   pacman-key --init
   pacman -Syu
   pacman -S mingw-w64-x86_64-cmake mingw-w64-x86_64-extra-cmake-modules
   pacman -S mingw-w64-x86_64-make
   pacman -S mingw-w64-x86_64-gdb
   pacman -S mingw-w64-x86_64-toolchain
    ```
3. clone project：`git clone https://github.com/ystyle/exatorrent/` (already setup `make app-windows-amd64`)
4. compile
    ```shell
    cd ${exatorrent-path}
    make app-windows-amd64
    ```

![image](https://user-images.githubusercontent.com/4478635/131999615-89e21ce4-db90-4433-b871-358d15b7bcb5.png)
![image](https://user-images.githubusercontent.com/4478635/131999661-2b67ff66-588f-427d-aad5-4ab41c721618.png)
![image](https://user-images.githubusercontent.com/4478635/131999703-b8a054d3-50db-4b67-ab5e-f2f005b52c6f.png)
![image](https://user-images.githubusercontent.com/4478635/131999716-c71f49bc-7ffa-4aef-99c3-a55b48e9eff7.png)

It seems to be running normally

**Comment by varbhat** [comment]
@ystyle ,

Thank you very much. 

Also , does `make web` work in windows (i used unix pathname) ?

**Comment by varbhat** [comment]
@ystyle  ,

Please see https://github.com/varbhat/exatorrent/commit/cc3afc8a38a27c432ade648790ccd7e17eecb1d9 .

Also , I have successfully cross compiled for MacOS , so expect some progress regarding that.

**Comment by ystyle** [comment]
@varbhat 

The path has no errors and can be displayed normally.
In addition, `esbuild.config.js` needs to be modified when compiling in my node environment
```js
import esbuild from'esbuild';
const {build} = esbuild;
```
Because the esbuild package only contains the CommonJS specification

**Comment by varbhat** [comment]
@ystyle ,

https://github.com/varbhat/exatorrent/issues/15#issuecomment-913694563
