### ISSUE TITLE
Dlna

### ISSUE THREAD

**Issue by lodgnewt** [varbhat/exatorrent#45]
Are there any plans to add support dlna?

**Comment by varbhat** [comment]
Currently , No. 

But , exatorrent provides downloading/streaming over direct HTTP endpoint ( Direct link; Must be authenticated; See API).

But dlna really useful / necessary ? I would like to discuss . Also contributions are welcome regarding this (it must also not bloat the application)

**Comment by anacrolix** [comment]
@varbhat You could consider https://github.com/anacrolix/dms if it's in scope.

**Comment by varbhat** [comment]
@anacrolix , Thanks. Will look into it(it might be another standalone program that needs to be run alongside exatorrent)
