### ISSUE TITLE
Incorrect encoding of Chinese files/folders in download directory

### ISSUE THREAD

**Issue by lxzan** [varbhat/exatorrent#464]
```
magnet:?xt=urn:btih:0a5e2cbebf846baffd106bc01855bec11f6bd4e9
```

![image](https://github.com/varbhat/exatorrent/assets/17956540/06bbf718-e2de-4935-9844-7661c6275b18)

**Comment by mckaygerhard** [comment]
@lxzan  maybe i fyou details more your "issue" ?

**Comment by evrins** [comment]
this is an issue of invliad utf8 named torrent

I create an pr on https://github.com/anacrolix/torrent to support it

https://github.com/anacrolix/torrent/pull/915

**Comment by lxzan** [comment]
@evrins 

Brother, would you be interested in giving varbhat/exatorrent a pr? The ui is mediocre but the download speed is pretty fast.

**Comment by evrins** [comment]
after my pr is merged into [anacrolix/torrent](https://github.com/anacrolix/torrent)
I will create a pr to change torrent dependency version to fixed commit
