### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by AverageHumanoid** [varbhat/exatorrent#48]
I would like to suggest including native FreeBSD binaries for future releases or documentation and Make commands to compile on FreeBSD.

**Comment by varbhat** [comment]
@AverageHumanoid ,

Although i have not tested , exatorrent must be buildable on+for FreeBSD.

Just set CC and CXX to respective FreeBSD compilers, and `make app` , `make app-nobuildflag` or `make-nosl` and exatorrent will be built.

I am not against releasing exatorrent for FreeBSD but there are no FreeBSD cross compilers(or should be built) . You are welcome to work towards this.
