### ISSUE TITLE
windows hides the window and runs in the background

### ISSUE THREAD

**Issue by ystyle** [varbhat/exatorrent#53]
Add -d option:
https://github.com/syncthing/syncthing/blob/main/lib/osutil/hidden_windows.go#L10-L23

**Comment by varbhat** [comment]
How do you un-hide it ?

**Comment by ystyle** [comment]
There are several ways to hide in windows
1. Hide `go build -ldflags -H=windowsgui` when compiling, the disadvantage is that there is no window when double-clicking to open
2. In use option (the method of [link above](https://github.com/syncthing/syncthing/blob/main/lib/osutil/hidden_windows.go#L10-L23))

**Comment by varbhat** [comment]
I would like exatorrent to have same behaviour across platforms. this means that `-d` flag will be only available in windows.

What i would like is wrapper to exatorrent which executes exatorrent but in hidden mode like you mentioned. Will this suffice ?

**Comment by ystyle** [comment]
@varbhat 
In windows, do not add the option to hide windows, the cmd window will appear when you start the application in the startup item or task plan。
There is another way to use vb script, but I don’t like this method
