### ISSUE TITLE
[BUG] username with five or fewer characters fails silently

### ISSUE THREAD

**Issue by Porco-Rosso** [varbhat/exatorrent#58]
Creating an admin username at first start with 5 or fewer characters such as:
`exatorrent -admin "12345"` does not show any problems in the terminal, but does not allow to log in in the web interface. You just get "invalid credentials".

**Comment by varbhat** [comment]
Well,

It's because i forgot to check the length of username passed to program in `-admin` .

Thanks for reporting it. I will correct it in next release

**Comment by varbhat** [comment]
@Porco-Rosso ,

See https://github.com/varbhat/exatorrent/releases/tag/v0.0.3 . That bug has been solved
